# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect("student.db")
cur = conn.cursor()

cur.executescript("""
CREATE TABLE students(
id INTEGER PRIMARY KEY,
name TEXT
);

CREATE TABLE courses(
id INTEGER PRIMARY KEY,
name TEXT
);

CREATE TABLE enrollments(
student_id INTEGER,
course_id INTEGER,
semester TEXT,
grade INTEGER
);
""")

cur.executescript("""
INSERT INTO students VALUES
(1,'Alice'),
(2,'Bob'),
(3,'Charlie'),
(4,'David');

INSERT INTO courses VALUES
(1,'SQL'),
(2,'Python');

INSERT INTO enrollments VALUES
(1,1,'Sem1',85),
(1,1,'Sem2',90),
(2,1,'Sem1',80),
(2,1,'Sem2',88),
(3,1,'Sem1',75),
(3,2,'Sem2',92),
(4,2,'Sem1',89),
(4,2,'Sem2',95);
""")
conn.commit()

query="""
WITH student_course_avg AS(
SELECT
e.course_id,
c.name AS course_name,
e.student_id,
s.name AS student_name,
AVG(e.grade) AS avg_grade
FROM enrollments e
JOIN students s ON s.id=e.student_id
JOIN courses c ON c.id=e.course_id
GROUP BY e.course_id,c.name,e.student_id,s.name
)
SELECT *,
RANK() OVER(PARTITION BY course_id ORDER BY avg_grade DESC) AS rnk
FROM student_course_avg;
"""
pd.read_sql(query,conn)

query="""
WITH course_scores AS(
SELECT
e.course_id,
c.name AS course_name,
e.student_id,
s.name AS student_name,
AVG(e.grade) AS avg_grade
FROM enrollments e
JOIN students s ON s.id=e.student_id
JOIN courses c ON c.id=e.course_id
GROUP BY e.course_id,c.name,e.student_id,s.name
)
SELECT
course_name,
student_name,
avg_grade,
PERCENT_RANK() OVER(PARTITION BY course_id ORDER BY avg_grade) AS pct_rank,
NTILE(4) OVER(PARTITION BY course_id ORDER BY avg_grade) AS quartile
FROM course_scores;
"""
pd.read_sql(query,conn)

query="""
WITH student_sem_avg AS(
SELECT
e.student_id,
s.name AS student_name,
semester,
AVG(grade) AS sem_avg
FROM enrollments e
JOIN students s ON s.id=e.student_id
GROUP BY e.student_id,s.name,semester
)
SELECT
student_name,
semester,
sem_avg,
AVG(sem_avg) OVER(
PARTITION BY student_name
ORDER BY semester
ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
) AS running_avg
FROM student_sem_avg;
"""
pd.read_sql(query,conn)

query="""
WITH course_sem_avg AS(
SELECT
e.course_id,
c.name AS course_name,
semester,
AVG(grade) AS course_avg
FROM enrollments e
JOIN courses c ON c.id=e.course_id
GROUP BY e.course_id,c.name,semester
),
student_sem_avg AS(
SELECT
e.course_id,
e.student_id,
s.name AS student_name,
semester,
AVG(grade) AS student_avg
FROM enrollments e
JOIN students s ON s.id=e.student_id
GROUP BY e.course_id,e.student_id,s.name,semester
)
SELECT
student_name,
course_name,
student_avg,
course_avg,
student_avg-course_avg AS delta
FROM student_sem_avg s
JOIN course_sem_avg c
ON s.course_id=c.course_id
AND s.semester=c.semester;
"""
pd.read_sql(query,conn)

cur.executescript("""
CREATE VIEW vw_course_stats AS
SELECT
c.id AS course_id,
c.name AS course_name,
AVG(e.grade) AS avg_grade,
MIN(e.grade) AS min_grade,
MAX(e.grade) AS max_grade,
COUNT(*) AS assessments
FROM enrollments e
JOIN courses c
ON c.id=e.course_id
GROUP BY c.id,c.name;
""")
conn.commit()

pd.read_sql("SELECT * FROM vw_course_stats;",conn)